title: Homebrew Documentation
description: Documentation for the missing package manager for macOS.

remote_theme: benbalter/retlab

exclude:
  - bin
  - CNAME
  - Gemfile*
  - vendor

plugins:
  - jekyll-feed
  - jekyll-remote-theme
  - jekyll-seo-tag
  - jekyll-sitemap
  

